#!/bin/sh
#
: <<=cut

=head1 NAME

mediaspip_sites - Nombre de sites mediaspip

=head1 APPLICABLE SYSTEMS

Tout système linux

=head1 CONFIGURATION

Pas de configuration

=head2 EXAMPLE WARNING AND CRITICAL SETTINGS

=head1 INTERPRETATION

Nombre de sites mediaspip

=head1 VERSION

  $Id: mediaspip_sites.in 3213 2009-12-10 13:31:49Z janl $

=head1 BUGS

Bugs ?

=head1 AUTHOR

Association INFINI - Eric Talarmain

=head1 LICENSE

GPLv2

=cut


. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	if [ -r /var/www/mediaspip/sites ]; then
		echo yes
	else
		echo no
	fi
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title Sites MediaSPIP'
	echo 'graph_vlabel nb'
	echo 'graph_info Ce graphe montre des statistiques sur l utilisation de mediaspip.'
	echo 'graph_category mediaspip'

	echo 'sites.label NbSites'
	echo 'sites.type GAUGE'
	echo 'sites.draw LINE1'
	echo "sites.info Nombre de sites MediaSPIP"

	exit 0
fi

nb_sites_test=0 # Sites de test : 
nb_sites=`find /var/www/mediaspip/sites/ -mindepth 1 -maxdepth 1 -type d | wc -l`
nb_sites=`expr $nb_sites - $nb_sites_test`
echo "sites.value ${nb_sites}"
